LobShooter for Oracle (oraload): Lob Class Reference
Lob Class Reference
#include <Lob.hpp>
Public Member Functions
void setFilename (string f)
void setSqlLocator (string sl)
int InitLob (string pField, string pTable, string pWhere)
Protected Attributes
string filename
string sqlLocator
Detailed Description
Lob
-----------
Base Lob Class
Author: Ralf Duenkelmann
Date : 01.06.2004
Member Function Documentation
void Lob::setFilename (string f)
setFilename set the filename for Lob (Up- and Download)
Parameters:
f filename
References filename.
Referenced by LobWizard::accept(), main(), TestSuite::runBinLobTest(), TestSuite::runBinLobTest_MultipleFiles(), TestSuite::runCharLobTest(), and TestSuite::runFaultySql().
void Lob::setSqlLocator (string sl)
setSqlLocator set the SQL to access the lob in the database
if inserting the lob attribute must be initialized before (use IniotLob or empty_clob() via direct SQL)
for inserting a LOB sqlLocator MUST be an select string Dont forget the locking via "for update" - clause!!
Parameters:
sl The SQL statement
References sqlLocator.
Referenced by LobWizard::accept(), main(), TestSuite::runBinLobTest(), TestSuite::runBinLobTest_MultipleFiles(), TestSuite::runCharLobTest(), and TestSuite::runFaultySql().
int Lob::InitLob (string pField, string pTable, string pWhere)
InitLob Initialize an empty Lob
Parameters:
pField The tables attribut where the lob is
pTable table name
pWhere where clause
References Conn::conn, Conn::getConnectorType(), BasicDML::sqlStmt, BasicDML::stmt, and Log::WriteLogFile().
Member Data Documentation
string Lob::filename [protected]
Referenced by BinLob::BinLob(), CharLob::CharLob(), BinLob::DownloadBlobData(), CharLob::DownloadClobData(), setFilename(), BinLob::UploadBlobData(), and CharLob::UploadClobData().
string Lob::sqlLocator [protected]
Referenced by BinLob::DownloadBlobData(), CharLob::DownloadClobData(), setSqlLocator(), BinLob::UploadBlobData(), and CharLob::UploadClobData().
The documentation for this class was generated from the following files:
lib/Lob.hpp
lib/Lob.cpp