LobShooter for Oracle (oraload): BinLob Class Reference
BinLob Class Reference
#include <BinLob.hpp>
Public Member Functions
BinLob ()
BinLob (char *user, char *pass, char *db, char *cfile)
BinLob (char *user, char *pass, char *db)
BinLob (oracle::occi::Connection *p_connection, oracle::occi::Environment *p_env)
~BinLob ()
int DownloadBlobData (void)
int UploadBlobData (void)
Detailed Description
BinLob
-----------
Upload and Download of Binary Lobs to an Oracle Server
Author: Ralf Duenkelmann
Date : 01.06.2004
Constructor & Destructor Documentation
BinLob::BinLob ()
Def Constructor
BinLob::BinLob (char * user, char * pass, char * db, char * cfile)
Constructor
Parameters:
user name of the database user
pass password of the database user
db The database alias from tnsnames
cfile filename to up- or download (full path)
default values of username & password
References Lob::filename, Conn::password, Conn::url, and Conn::username.
BinLob::BinLob (char * user, char * pass, char * db)
Constructor
Parameters:
user name of the database user
pass password of the database user
db The database alias from tnsnames
default values of username & password
References Conn::password, Conn::url, and Conn::username.
BinLob::BinLob (oracle::occi::Connection * p_connection, oracle::occi::Environment * p_env)
Constructor
Parameters:
connection name of a formerly built connection
connection the corresponding environment
References Conn::conn, and Conn::env.
BinLob::~BinLob ()
Def Destructor
Member Function Documentation
int BinLob::DownloadBlobData (void)
DownloadBlob Download it
Returns:
0 ok , -1 file open problem , -3 Oracle Error
References Conn::conn, Lob::filename, Conn::getConnectorType(), Lob::sqlLocator, BasicDML::stmt, and Log::WriteLogFile().
Referenced by LobWizard::accept(), main(), and TestSuite::runBinLobTest().
int BinLob::UploadBlobData (void)
UploadBlob Upload it
Returns:
0 ok , -1 file open problem , -3 Oracle Error
References Conn::conn, Lob::filename, Conn::getConnectorType(), Lob::sqlLocator, BasicDML::stmt, and Log::WriteLogFile().
Referenced by LobWizard::accept(), main(), TestSuite::runBinLobTest(), and TestSuite::runBinLobTest_MultipleFiles().
The documentation for this class was generated from the following files:
lib/BinLob.hpp
lib/BinLob.cpp