LobShooter for Oracle (oraload): Conn Class Reference
Conn Class Reference
#include <Connection.hpp>
Public Member Functions
Conn ()
Conn (string pConnectorType)
~Conn ()
void setConnectorType (string c)
string getConnectorType (void)
void setUsername (string u)
void setPassword (string p)
void setUrl (string u)
int connect (void)
Protected Attributes
string ConnectorType
string username
string password
string url
oracle::occi::Connection * conn
oracle::occi::Environment * env
Constructor & Destructor Documentation
Conn::Conn ()
References setConnectorType().
Conn::Conn (string pConnectorType)
References setConnectorType().
Conn::~Conn ()
Member Function Documentation
void Conn::setConnectorType (string c)
References ConnectorType.
Referenced by Conn().
string Conn::getConnectorType (void)
References ConnectorType.
Referenced by connect(), BasicDML::displayRows(), BinLob::DownloadBlobData(), CharLob::DownloadClobData(), Lob::InitLob(), BasicDML::InsertRow(), BinLob::UploadBlobData(), and CharLob::UploadClobData().
void Conn::setUsername (string u)
References username.
Referenced by LobWizard::lw_connect(), and TestSuite::runConnTest().
void Conn::setPassword (string p)
References password.
Referenced by LobWizard::lw_connect(), and TestSuite::runConnTest().
void Conn::setUrl (string u)
References url.
Referenced by LobWizard::lw_connect(), and TestSuite::runConnTest().
int Conn::connect (void)
References conn, env, getConnectorType(), password, url, username, and Log::WriteLogFile().
Referenced by LobWizard::lw_connect(), main(), TestSuite::runBasicDMLTest(), TestSuite::runBinLobTest(), TestSuite::runBinLobTest_MultipleFiles(), TestSuite::runCharLobTest(), TestSuite::runConnTest(), and TestSuite::runFaultySql().
Member Data Documentation
string Conn::ConnectorType [protected]
Referenced by getConnectorType(), and setConnectorType().
string Conn::username [protected]
Referenced by BasicDML::BasicDML(), BinLob::BinLob(), CharLob::CharLob(), connect(), and setUsername().
string Conn::password [protected]
Referenced by BasicDML::BasicDML(), BinLob::BinLob(), CharLob::CharLob(), connect(), and setPassword().
string Conn::url [protected]
Referenced by BasicDML::BasicDML(), BinLob::BinLob(), CharLob::CharLob(), connect(), and setUrl().
oracle::occi::Connection* Conn::conn [protected]
Referenced by LobWizard::accept(), BinLob::BinLob(), CharLob::CharLob(), connect(), BasicDML::displayRows(), BinLob::DownloadBlobData(), CharLob::DownloadClobData(), BasicDML::getInt(), BasicDML::getString(), Lob::InitLob(), BasicDML::InsertRow(), BinLob::UploadBlobData(), and CharLob::UploadClobData().
oracle::occi::Environment* Conn::env [protected]
Referenced by LobWizard::accept(), BinLob::BinLob(), CharLob::CharLob(), and connect().
The documentation for this class was generated from the following files:
lib/Connection.hpp
lib/Connection.cpp