LobShooter for Oracle (oraload): CharLob Class Reference
CharLob Class Reference
#include <CharLob.hpp>
Public Member Functions
CharLob ()
CharLob (char *user, char *pass, char *db, char *cfile)
CharLob (char *user, char *pass, char *db)
CharLob (oracle::occi::Connection *p_connection, oracle::occi::Environment *p_env)
~CharLob ()
int DownloadClobData (void)
int UploadClobData (void)
void setCharSet (string pCharSet)
string getCharSet ()
Private Attributes
string char_set
Detailed Description
CharLob
-----------
Upload and Download of Character Lobs to an Oracle Server
Author: Ralf Duenkelmann
Date : 01.06.2004
Constructor & Destructor Documentation
CharLob::CharLob ()
Def Constructor
CharLob::CharLob (char * user, char * pass, char * db, char * cfile)
Constructor
Parameters:
user name of the database user
pass password of the database user
db The database alias from tnsnames
cfile filename to up- or download (full path)
default values of username & password
References Lob::filename, Conn::password, Conn::url, and Conn::username.
CharLob::CharLob (char * user, char * pass, char * db)
Constructor
Parameters:
user name of the database user
pass password of the database user
db The database alias from tnsnames
default values of username & password
References Conn::password, Conn::url, and Conn::username.
CharLob::CharLob (oracle::occi::Connection * p_connection, oracle::occi::Environment * p_env)
Def Constructor
Constructor
Parameters:
connection name of a formerly built connection
connection the corresponding environment
References Conn::conn, and Conn::env.
CharLob::~CharLob ()
Member Function Documentation
int CharLob::DownloadClobData (void)
DownloadBlob Download it
Returns:
0 ok , -1 file open problem , -3 Oracle Error
References Conn::conn, Lob::filename, getCharSet(), Conn::getConnectorType(), Lob::sqlLocator, BasicDML::stmt, and Log::WriteLogFile().
Referenced by LobWizard::accept(), main(), TestSuite::runCharLobTest(), and TestSuite::runFaultySql().
int CharLob::UploadClobData (void)
UploadClob Upload it
Returns:
0 ok , -1 file open problem , -3 Oracle Error
References Conn::conn, Lob::filename, getCharSet(), Conn::getConnectorType(), Lob::sqlLocator, BasicDML::stmt, and Log::WriteLogFile().
Referenced by LobWizard::accept(), main(), and TestSuite::runCharLobTest().
void CharLob::setCharSet (string pCharSet)
References char_set.
Referenced by LobWizard::accept(), and main().
string CharLob::getCharSet ()
References char_set.
Referenced by DownloadClobData(), and UploadClobData().
Member Data Documentation
string CharLob::char_set [private]
Referenced by getCharSet(), and setCharSet().
The documentation for this class was generated from the following files:
lib/CharLob.hpp
lib/CharLob.cpp