LobShooter for Oracle (oraload): oraload/main.cpp File Reference
oraload/main.cpp File Reference
#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <cstdio>
#include <time.h>
#include <occi.h>
#include "CharLob.hpp"
#include "BinLob.hpp"
#include "Log.hpp"
#include "LobWizard.h"
Functions
static string const VERSION ("0.2.2")
static string vLogFile ("oraload.log")
static string vCharSet ("UTF8")
void Version ()
void Usage (char *vProg)
int main (int argc, char *argv[])
Variables
int multifile = 0
Function Documentation
int main (int argc, char * argv[])
References Conn::connect(), BinLob::DownloadBlobData(), CharLob::DownloadClobData(), Log::FlushLogFile(), CharLob::setCharSet(), Lob::setFilename(), Log::setLogFile(), Lob::setSqlLocator(), BinLob::UploadBlobData(), CharLob::UploadClobData(), Usage(), vCharSet(), Version(), vLogFile(), and Log::WriteLogFile().
void Usage (char * vProg)
Referenced by main().
static string vCharSet ("UTF8") [static]
Referenced by main().
void Version ()
References VERSION().
Referenced by main().
static string const VERSION ("0.2.2") [static]
Referenced by Version().
static string vLogFile ("oraload.log") [static]
Referenced by main().
Variable Documentation
int multifile = 0